# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      - image: mysql:5.7
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx4600m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      # install mysql client
      - run: sudo apt install -y mysql-client
      # create database 
      - run:
          name: Mysql database
          command: mysql  -h 127.0.0.1 -u root -e "CREATE DATABASE webspringdb;"    
      # migrate database
      - run: mvn flyway:migrate -Dflyway.user=root -Dflyway.url=jdbc:mysql://localhost:3306?serverTimezone=Europe/Budapest -Dflyway.password= -Dflyway.schemas=webspringdb
      # run tests!
      - run: mvn -X integration-test

      - store_artifacts:
          path: target
          destination: build

      - store_test_results:
          path: target/surefire-reports
          
      - run: mvn -X javadoc:javadoc
